### ISSUE TITLE
Unable to set license header styles

### ISSUE THREAD

**Issue by TheSilkMiner** [CadixDev/licenser#10]
### Description
I am currently working on a project where I am mixing some Java and some Kotlin source files, every single one of them without a license header.
At first I attempted to run the `checkLicense` task with the following configuration:
```gradle
license {
    header = project.file('COPYING')

    include '**/*.java'
    include '**/*.kt'

    ext { /* Unnecessary */ }

    ignoreFailures = false

    style {
        java = 'BLOCK_COMMENT'
        kt = 'BLOCK_COMMENT'
    }
}
```
The build succeeded even if no one of the files present had the correct header. On the other hand, the plugin complained for every single file, both Java and Kotlin, that it could not find a matching header format.
After this, I tried finding out the source of the problem and, with some commenting, the build successfully failed when I commented out the entire `style` block. It seems like providing custom license header styles makes the plugin not only forget the defaults, but also not apply the specified styles.
I attached logs of both the run with the `style` block and the one without it.
In case you want to have a look at the setup of the entire project, it is available at [TheSilkMiner/SKL-Java-Interpreter@0.3 (commit 8b4063f)](https://github.com/TheSilkMiner/SKL-Java-Interpreter/tree/8b4063f06c4ff4169fd6f32cfa959e11966808bb).

### Logs
<details>
<summary><strong>Output of <code>./gradlew checkLicense --info --stacktrace</code> with <code>style</code> block</strong></summary>

```text
Initialized native services in: C:\Users\thesi\.gradle\native
Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: C:\Users\thesi\.gradle\daemon\4.9 Command: C:\Program Files\Java\jdk1.8.0_171\bin\java.exe -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\thesi\.gradle\wrapper\dists\gradle-4.9-all\491wbe0x5d54n9cojs2p0zv90\gradle-4.9\lib\gradle-launcher-4.9.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.9
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 7.242 secs.
The client will now receive all logging from the daemon (pid: 10656). The daemon log file: C:\Users\thesi\.gradle\daemon\4.9\daemon-10656.out.log
Starting build in new daemon [memory: 954.7 MB]
Using 2 worker leases.
Starting Build
Settings evaluated using settings file 'E:\GitHub\SKL-Java-Interpreter\settings.gradle'.
Projects loaded. Root project using build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle'.
Included projects: [root project 'SKL-Java-Interpreter']
Parallel execution is an incubating feature.

> Configure project :
Evaluating root project 'SKL-Java-Interpreter' using build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle'.
Compiling build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle' using SubsetScriptTransformer.
Compiling build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle' using BuildScriptTransformer.
All projects evaluated.
Selected primary task 'checkLicenses' from project :
Tasks to be executed: [task ':checkLicenseMain', task ':checkLicenseTest', task ':checkLicenses']
:checkLicenseMain (Thread[Daemon worker,5,main]) started.

> Task :checkLicenseMain
Task ':checkLicenseMain' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
No matching header format found for src\main\java\net\thesilkminer\skl\interpreter\api\skd\exceptions\IllegalDatabaseSyntaxException.java
No matching header format found for src\main\java\net\thesilkminer\skl\interpreter\api\skd\holder\IDatabaseHolder.java
=== SNIPPED EQUAL LINES ===
No matching header format found for src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\parser\Utilities.kt
No matching header format found for src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\Support.kt
:checkLicenseMain (Thread[Daemon worker,5,main]) completed. Took 1.942 secs.
:checkLicenseTest (Thread[Daemon worker,5,main]) started.

> Task :checkLicenseTest
Task ':checkLicenseTest' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
No matching header format found for src\test\java\org\apache\log4j\custom\MultipleFilesAppender.java
No matching header format found for src\test\kotlin\net\thesilkminer\skl\interpreter\skd\structure\ArrayEntityBaseTest.kt
=== SNIPPED EQUAL LINES ===
No matching header format found for src\test\kotlin\net\thesilkminer\skl\interpreter\skd\structure\PropertyBaseTest.kt
No matching header format found for src\test\kotlin\net\thesilkminer\skl\interpreter\skd\tools\parser\DeclaratorTest.kt
:checkLicenseTest (Thread[Daemon worker,5,main]) completed. Took 0.045 secs.
:checkLicenses (Thread[Task worker for ':',5,main]) started.

> Task :checkLicenses
Skipping task ':checkLicenses' as it has no actions.
:checkLicenses (Thread[Task worker for ':',5,main]) completed. Took 0.001 secs.

BUILD SUCCESSFUL in 39s
2 actionable tasks: 2 executed
```
</details>

<details>
<summary><strong>Output of <code>./gradlew checkLicense --info --stacktrace</code> without <code>style</code> block</strong></summary>

```text
Initialized native services in: C:\Users\thesi\.gradle\native
The client will now receive all logging from the daemon (pid: 10656). The daemon log file: C:\Users\thesi\.gradle\daemon\4.9\daemon-10656.out.log
Starting 3rd build in daemon [uptime: 2 mins 49.212 secs, performance: 99%, no major garbage collections]
Using 2 worker leases.
Starting Build
Settings evaluated using settings file 'E:\GitHub\SKL-Java-Interpreter\settings.gradle'.
Projects loaded. Root project using build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle'.
Included projects: [root project 'SKL-Java-Interpreter']
Parallel execution is an incubating feature.

> Configure project :
Evaluating root project 'SKL-Java-Interpreter' using build file 'E:\GitHub\SKL-Java-Interpreter\build.gradle'.
All projects evaluated.
Selected primary task 'checkLicenses' from project :
Tasks to be executed: [task ':checkLicenseMain', task ':checkLicenseTest', task ':checkLicenses']
:checkLicenseMain (Thread[Daemon worker Thread 2,5,main]) started.

> Task :checkLicenseMain FAILED
Task ':checkLicenseMain' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:checkLicenseMain (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.516 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkLicenseMain'.
> License violations were found: src\main\java\net\thesilkminer\skl\interpreter\api\skd\exceptions\IllegalDatabaseSyntaxException.java, src\main\java\net\thesilkminer\skl\interpreter\api\skd\holder\IDatabaseHolder.java, **SNIP** src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\parser\Utilities.kt, src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\Support.kt

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkLicenseMain'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
=== SNIPPED INTERNAL GRADLE CALLS ===
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: net.minecrell.gradle.licenser.LicenseViolationException: License violations were found: src\main\java\net\thesilkminer\skl\interpreter\api\skd\exceptions\IllegalDatabaseSyntaxException.java, src\main\java\net\thesilkminer\skl\interpreter\api\skd\holder\IDatabaseHolder.java, **SNIP** src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\parser\Utilities.kt, src\main\kotlin\net\thesilkminer\skl\interpreter\skd\tools\Support.kt
        at net.minecrell.gradle.licenser.tasks.LicenseCheck.checkFiles(LicenseCheck.groovy:73)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 111 more


* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed
```
</details>

### Platform details
**Licenser version:** 0.4.1, added through `plugins` block
**Gradle version:** 4.9
**Groovy version:** 2.4.12
**Java version:** JDK 1.8.0u171 64-bit
**OS:** Windows 10 Home 64-bit (17735.rs5_release.180807-1451)
<details><summary><strong>Gradle daemon properties:</strong></summary>

```properties
# Gradle daemon related properties
org.gradle.warning.mode=all
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.console=auto
org.gradle.caching.debug=true
```
</details>

### Probable resolution hypothesis (based on commit e3a1b379a7223862bca96fc4b4aaa6501ff50a4b)
**Note: the following assumptions are solely based on speculations and are not tested.**
The `license` block in-code counterpart is the `LicenseExtension.groovy` file. There, [on line 76](https://github.com/Minecrell/licenser/blob/e3a1b379a7223862bca96fc4b4aaa6501ff50a4b/src/main/groovy/net/minecrell/gradle/licenser/LicenseExtension.groovy#L76), the `style` property is specified as an instance of `HeaderFormatRegistry`, i.e. a child of `CaseInsensitiveMap` with a more specific handling for `HeaderFormat`s.
The `style` property may thus be initialized as a "normal" `CaseInsensitiveMap<String>`. Its contents can then be used in the task to first create a `HeaderFormatRegistry` with the default `HeaderStyle`s and then override the few specified in the `style` property.

**Comment by Minecrell** [comment]
Thanks a lot for the detailed report! I will take a closer look at this soon.

For now, you can keep the `style` block commented out or even remove it entirely; `BLOCK_COMMENT` is the default for both Java and Kotlin.

**Comment by MinecraftPlaye** [comment]
I've also got this problem: `No matching header format found for src\main\java\minecraftplaye\project\IProxy.java`
Thought I cannot comment out the `style` block as I'm using `java = 'JAVADOC'` and not `BLOCK_COMMENT`.


`Selected primary task 'checkLicenses' from project :
Tasks to be executed: [task ':checkLicenseMain', task ':checkLicenses']
:checkLicenseMain (Thread[Task worker for ':',5,main]) started.

> Task :checkLicenseMain
Task ':checkLicenseMain' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
No matching header format found for src\main\java\minecraftplaye\project\IProxy.java
:checkLicenseMain (Thread[Task worker for ':',5,main]) completed. Took 0.036 secs.
:checkLicenses (Thread[Task worker for ':',5,main]) started.

> Task :checkLicenses
Skipping task ':checkLicenses' as it has no actions.
:checkLicenses (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.`
