### ISSUE TITLE
Gradle 8 deprecations

### ISSUE THREAD

**Issue by josephjthomas** [CadixDev/licenser#39]
I built my project with Gradle 7.4 today and noticed the following warning for licenser:

> Task :checkLicenseMain NO-SOURCE
> Relying on FileTrees for ignoring empty directories when using @SkipWhenEmpty has been deprecated. This is scheduled to be removed in Gradle 8.0. Annotate the property matchingFiles with @IgnoreEmptyDirectories or remove @SkipWhenEmpty. Consult the upgrading guide for further information: https://docs.gradle.org/7.4/userguide/upgrading_version_7.html#empty_directories_file_tree

I'm using licenser 0.6.1

**Comment by jpenilla** [comment]
Gradle 8 is now released, would be great to have a release with the latest changes.

**Comment by jamierocks** [comment]
Quite right. I'll take a stab at this at the weekend.

**Comment by jpenilla** [comment]
New warning in 8.3:
```
The org.gradle.util.ConfigureUtil type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#org_gradle_util_reports_deprecations
        at org.gradle.util.ConfigureUtil.logDeprecation(ConfigureUtil.java:215)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:148)
        at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
        at org.cadixdev.gradle.licenser.Licenser$_makeTask_closure13.doCall(Licenser.groovy:225)
```
